### ISSUE TITLE
Contract Constructor

### ISSUE THREAD

**Issue by felgarte** [paulvidal/CryptoMons#1]
Hey @paulvidal nice to write you!
I was searching ERC721 examples at github and I found this great code. I would like to ask you if you can share the contract's constructor to understand all the process.
I don't know if you have twitter to follow you and bother you with DM's 🤓

**Comment by paulvidal** [comment]
Hi @felgarte :) Of course feel free to share! I don t have twitter unfortunately :%

**Comment by paulvidal** [comment]
Hi @felgarte all the contract code can be found in the contracts folder :)

**Comment by felgarte** [comment]
Sure! I know all te contract is right there, but I would like tha part of the contract deploy (when we need to set up and send to constructors all the required parameters)
